In [30]:
import torch
print(torch.__version__)

2.5.1+cu121


In [31]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


# Creating a Tensor

In [32]:
# using empty
a = torch.empty(2,3)

In [33]:
# check type
type(a)

torch.Tensor

In [34]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
# using rand
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [37]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [38]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [39]:
# other ways

# arrange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((2,3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shape

In [40]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [41]:
x.shape

torch.Size([2, 3])

In [42]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6066966817701702964, 3978149828805407026, 6500720907931366958]])

In [43]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [50]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [46]:
# find data type
x.dtype

torch.int64

In [47]:
# assign data type
torch.tensor([[1.0,2.0,3.0], [4.0,5.0,6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [48]:
torch.tensor([1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [49]:
# using to() -> It is used to convert the datatype of tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathematical Operations

1. **Scaler Operation**

In [51]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [59]:
# Addition
x + 2
# Substraction
x - 2
# Multiplication
x * 2
# Division
x / 2
# int Division
(x * 100)//3
# Mod
((x * 100)//3)%2
# Power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# Element wise Operation

In [60]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [66]:
# Add
a + b

# Sub
a - b

# Multiply
a * b

# Divide
a / b

# Power
a**b

# Mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [67]:
c = torch.tensor([1,-2,3,-4])

In [68]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [69]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [70]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [71]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [72]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [73]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [74]:
# clamp
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation

In [79]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [80]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim = 0)

# sum along rows
torch.sum(e, dim = 1)

tensor([15., 13.])

In [81]:
# mean
torch.mean(e)

# mean along columns
torch.mean(e, dim = 0)

# mean along rows
torch.mean(e, dim = 1)

tensor([5.0000, 4.3333])

In [82]:
# median
torch.median(e)

# median along columns
torch.median(e, dim = 0)

# median along rows
torch.median(e, dim = 1)

torch.return_types.median(
values=tensor([5., 4.]),
indices=tensor([0, 1]))

In [83]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product